#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Allow mpirun as root (Docker)
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

NPROCS=$(foamDictionary -entry numberOfSubdomains -value system/decomposeParDict)

echo "Copying 'initial' to 0"
cp -r initial 0

blockMesh 2>&1 | tee log.blockMesh
setFields 2>&1 | tee log.setFields

if [ "$NPROCS" -gt 1 ]; then
    decomposePar 2>&1 | tee log.decomposePar
    mpirun --oversubscribe -np "$NPROCS" laserbeamFoam -parallel 2>&1 | tee log.laserbeamFoam
else
    laserbeamFoam 2>&1 | tee log.laserbeamFoam
fi
