#!/bin/bash
# -----------------------------------------------------------------------------
# Allrun script for LPBF Sensitivity Study
# -----------------------------------------------------------------------------

set -e

# Sourced OpenFOAM environment
source /usr/lib/openfoam/openfoam2412/etc/bashrc || true

# Sourced python virtual environment if available, otherwise just use standard python3
if [ -d "../../../../venv314" ]; then
    source ../../../../venv314/bin/activate
elif [ -d "../../venv314" ]; then
    source ../../venv314/bin/activate
fi

# Execute sensitivity study orchestrator
python3 scripts/run_sensitivity_study.py
